export enum NotificationType {
  MACHINE_CREATED = 'MACHINE_CREATED',
  INFO = 'INFO',
  ALERT = 'ALERT',
  RAW_MATERIAL_LOW_STOCK = 'RAW_MATERIAL_LOW_STOCK',
  SHIFT_CREATED = 'SHIFT_CREATED',
  SHIFT_EDITED = 'SHIFT_EDITED',
  SHIFT_DELETED = 'SHIFT_DELETED',
  MAINTENANCE_TICKET_CREATED = 'MAINTENANCE_TICKET_CREATED',
  MAINTENANCE_TICKET_UPDATED = 'MAINTENANCE_TICKET_UPDATED',
  MAINTENANCE_TICKET_DELETED = 'MAINTENANCE_TICKET_DELETED',
  MAINTENANCE_TICKET_CLOSED = 'MAINTENANCE_TICKET_CLOSED',
}
