export enum NotificationType {
  MACHINE_CREATED = 'MACHINE_CREATED',
  INFO = 'INFO',
  ALERT = 'ALERT',
  RAW_MATERIAL_LOW_STOCK = 'RAW_MATERIAL_LOW_STOCK',
  SHIFT_CREATED = 'SHIFT_CREATED',
  SHIFT_EDITED = 'SHIFT_EDITED',
  SHIFT_DELETED = 'SHIFT_DELETED',
}
