export const MESSAGE_CONSTANTS = {
  ERROR: {
    USER_NOT_FOUND: 'User not found',
    USER_NOT_UPDATED: 'User not updated',
    USER_NOT_AUTHORIZED_CREATE_TENANT:
      'User is not authorized to create tenant',
    EMAIL_REQUIRED: 'Email is required',
    USER_ROLE_MISSING: 'User role is missing',
    USER_ALREADY_VERIFIED: 'User is already verified',
    TOKEN_REQUIRED: 'Token is required',
    INVALID_EXPIRED_TOKEN: 'Invalid or expired token',
    TOKEN_EXPIRED: 'Token has expired',
    USER_ALREADY_EXISTS: 'User already exists try logging in',
    INVALID_EXPIRED_REFRESH_TOKEN: 'Invalid or expired refresh token',
    REFRESH_TOKEN_NOT_FOUND: 'Refresh token not found',
    USER_NOT_AUTHENTICATED: 'User not authenticated',
    USER_EMAIL_NOT_VERIFIED: 'User email is not verified',
    INVALID_CREDENTIALS: 'Invalid credentials',
    TENANT_NOT_FOUND: 'Tenant not found',
    ACCESS_DENIED_SUBDOMAIN:
      'Access denied: You do not have permission to access this subdomain.',
    NOT_ALLOWED_BY_CORS: 'Not allowed by CORS',
    INVALID_ORIGIN: 'Invalid Origin',
    TENANT_NAME_TAKEN: 'Tenant name already taken',
    FAILED_TO_UPDATE_TENANT: 'Failed to update tenant',
    FAILED_TO_CREATE_TENANT: 'Failed to create tenant',
    USER_ALREADY_HAS_TENANT: 'User already has a tenant',
    INTERNAL_SERVER_ERROR: 'Internal server error',
    FAILED_TO_CREATE_USER: 'Failed to create user',
    FAILED_TO_UPDATE_USER: 'Failed to update user',
    USER_IS_BLOCKED: 'User is blocked',
    USER_IS_DELETED: 'User is deleted',
    UNIQUE_CONSTRAINT_VIOLATION: 'Unique constraint violation',
    SUBSCRIPTION_NOT_FOUND: 'Subscription not found',
    ONLY_IMAGE_FILES_ALLOWED: 'Only image files are allowed!',
    FILE_IS_REQUIRED: 'File is required',
    MACHINE_NOT_FOUND: 'Machine not found',
    MACHINE_NAME_TAKEN: 'Machine name already exists, try another one',
    FAILED_TO_CREATE_MACHINE: 'Failed to create machine',
    FAILED_TO_UPDATE_MACHINE: 'Failed to update machine',
    MACHINE_ALREADY_DELETED: 'Machine is already deleted',
    FIXTURE_NOT_FOUND: 'Fixture not found',
    FIXTURE_NAME_TAKEN: 'Fixture name already exists, try another one',
    FAILED_TO_CREATE_FIXTURE: 'Failed to create fixture',
    FAILED_TO_UPDATE_FIXTURE: 'Failed to update fixture',
    FIXTURE_ALREADY_DELETED: 'Fixture is already deleted',
    RAW_MATERIAL_NOT_FOUND: 'Raw material not found',
    RAW_MATERIAL_NAME_TAKEN:
      'Raw material name already exists, try another one',
    FAILED_TO_CREATE_RAW_MATERIAL: 'Failed to create raw material',
    FAILED_TO_UPDATE_RAW_MATERIAL: 'Failed to update raw material',
    RAW_MATERIAL_ALREADY_DELETED: 'Raw material is already deleted',
    SUBSCRIPTION_EXPIRED:
      'Subscription has expired. Please upgrade to continue.',
    SUBSCRIPTION_RESTRICTED: 'Subscription is restricted. Access denied.',
    NO_SUBSCRIPTION_FOUND: 'No active subscription found for this tenant',
    TENANT_ID_MISSING: 'Tenant identification missing',
    FAILED_TO_CHECK_TENANT: 'Failed to check tenant',
    TENANT_IS_BLOCKED: 'Tenant is blocked',
    PLAN_NOT_FOUND: 'Plan not found',
    PAYMENT_NOT_FOUND: 'Payment not found',
    ACTIVE_PAID_SUBSCRIPTION_EXISTS:
      'Organization already has an active paid subscription',
    FREE_PLAN_ONLY: 'This endpoint is only for free plans',
    ACTIVE_SUBSCRIPTION_EXISTS:
      'Organization already has an active paid subscription',
    PAYMENT_ALREADY_SUCCEEDED: 'Payment has already succeeded',
    PAYMENT_NO_PLAN: 'Payment does not have an associated plan',
    INVALID_PAYMENT_SIGNATURE: 'Invalid payment signature',
    FREE_PLAN_ACTIVATION_BLOCKED:
      'Cannot activate free plan: an active paid subscription already exists',
    TRIAL_ALREADY_USED: 'Free trial has already been used by this organization',
    DELETE_NOT_IMPLEMENTED: 'Delete not implemented',
    PART_NOT_FOUND: 'Part not found',
    JOB_NOT_FOUND: 'Job not found',
    FAILED_TO_CREATE_JOB: 'Failed to create job',
    FAILED_TO_UPDATE_JOB: 'Failed to update job',
    INVALID_ASSIGNEE: 'Invalid assignee for this job',
    PART_NUMBER_TAKEN: 'Part number already exists, try another one',
    FAILED_TO_CREATE_PART: 'Failed to create part',
    FAILED_TO_UPDATE_PART: 'Failed to update part',
    ONLY_PDF_FILES_ALLOWED: 'Only PDF files are allowed!',
    PART_IN_USE:
      'Cannot delete part: it is currently associated with active jobs',
    MACHINE_IN_USE:
      'Cannot delete machine: it is currently associated with active parts',
    FIXTURE_IN_USE:
      'Cannot delete fixture: it is currently associated with active parts',
    RAW_MATERIAL_IN_USE:
      'Cannot delete raw material: it is currently associated with active parts',
    INSUFFICIENT_RAW_MATERIAL:
      'Insufficient raw material stock to fulfil this job quantity',
    NC_PROGRAM_NOT_FOUND: 'NC Program not found',
    NC_PROGRAM_NAME_TAKEN: 'NC Program name already exists, try another one',
    FAILED_TO_CREATE_NC_PROGRAM: 'Failed to create NC Program',
    FAILED_TO_UPDATE_NC_PROGRAM: 'Failed to update NC Program',
    INVALID_NC_FILE_TYPE:
      'Invalid NC file type. Allowed: .nc, .cnc, .tap, .ngc, .txt, .mpf, .ptp',
    VERSION_NOT_FOUND: 'Program version not found',
    CANNOT_DELETE_LAST_VERSION:
      'Cannot delete the final remaining valid version of a program',
  },
  VALIDATION: {
    EMAIL_INVALID: 'Please provide a valid email address',
    PASSWORD_MIN_LENGTH_8: 'Password must be at least 8 characters long',
    PASSWORD_MIN_LENGTH_6: 'Password must be at least 6 characters long',
    PASSWORD_MAX_LENGTH_12: 'Password must be at most 12 characters long',
    NAME_MIN_LENGTH_3: 'Name must be at least 3 characters long',
    NAME_MIN_LENGTH_2: 'Name must be at least 2 characters long',
    ROLE_INVALID: 'Invalid role',
  },
  SUCCESS: {
    USER_REGISTERED: 'User registered successfully',
    USER_CREATED: 'user sucessfully created this is from ApiResponse',
    USER_LOGGED_IN: 'user sucessfully logged in',
    USER_PROFILE: 'user profile',
    USER_UPDATED: 'user updated successfully',
    TOKEN_REFRESHED: 'token refreshed successfully',
    PASSWORD_RESET_LINK_SENT: 'Password reset link sent successfully',
    PASSWORD_RESET: 'Password reset successfully',
    EMAIL_VERIFIED: 'Email successfully verified',
    VERIFICATION_EMAIL_SENT: 'Verification email sent successfully',
    USER_LOGGED_OUT: 'user successfully logged out',
    TENANT_FETCHED: 'Tenant fetched successfully',
    TENANT_CREATED: 'Tenant created successfully',
    TENANT_UPDATED: 'Tenant updated successfully',
    ALL_TENANTS_FETCHED: 'All tenants fetched successfully',
    ALL_USERS_FETCHED: 'All users fetched successfully',
    TENANT_NAME_UPDATED: 'Tenant name updated successfully',
    SUBSCRIPTION_CREATED: 'Subscription created successfully',
    SUBSCRIPTION_FETCHED: 'Subscription fetched successfully',
    SUBSCRIPTION_UPDATED: 'Subscription updated successfully',
    PROFILE_IMAGE_UPLOADED: 'Profile image uploaded successfully',
    MACHINE_CREATED: 'Machine created successfully',
    MACHINE_UPDATED: 'Machine updated successfully',
    MACHINES_FETCHED: 'Machines fetched successfully',
    MACHINE_BLOCK_TOGGLED: 'Machine block status updated',
    MACHINE_DELETED: 'Machine deleted successfully',
    FIXTURE_CREATED: 'Fixture created successfully',
    FIXTURE_UPDATED: 'Fixture updated successfully',
    FIXTURES_FETCHED: 'Fixtures fetched successfully',
    FIXTURE_BLOCK_TOGGLED: 'Fixture block status updated',
    FIXTURE_DELETED: 'Fixture deleted successfully',
    RAW_MATERIAL_CREATED: 'Raw material created successfully',
    RAW_MATERIAL_UPDATED: 'Raw material updated successfully',
    RAW_MATERIALS_FETCHED: 'Raw materials fetched successfully',
    RAW_MATERIAL_BLOCK_TOGGLED: 'Raw material block status updated',
    RAW_MATERIAL_DELETED: 'Raw material deleted successfully',
    USER_DELETED: 'User deleted successfully',
    ORDER_CREATED: 'Order created successfully',
    PAYMENT_VERIFIED: 'Payment verified successfully',
    RETRY_ORDER_CREATED: 'New order created for retry',
    LATEST_PENDING_FETCHED: 'Latest pending payment fetched',
    FREE_PLAN_ACTIVATED: 'Free plan activated successfully',
    JOB_CREATED: 'Job created successfully',
    JOB_UPDATED: 'Job updated successfully',
    JOBS_FETCHED: 'Jobs fetched successfully',
    JOB_DELETED: 'Job deleted successfully',
    PART_CREATED: 'Part created successfully',
    PART_UPDATED: 'Part updated successfully',
    PARTS_FETCHED: 'Parts fetched successfully',
    PART_DELETED: 'Part deleted successfully',
    PART_BLOCK_TOGGLED: 'Part block status updated',
    NC_PROGRAM_CREATED: 'NC Program created successfully',
    NC_PROGRAM_UPDATED: 'NC Program updated successfully',
    NC_PROGRAMS_FETCHED: 'NC Programs fetched successfully',
    NC_VERSION_ADDED: 'NC Program version added successfully',
    NC_VERSION_BLOCK_TOGGLED: 'NC Program version block status updated',
    NC_VERSION_DELETED: 'NC Program version deleted successfully',
  },
};
