export const MESSAGE_CONSTANTS = {
  ERROR: {
    USER_NOT_FOUND: 'User not found',
    USER_NOT_UPDATED: 'User not updated',
    USER_NOT_AUTHORIZED_CREATE_TENANT:
      'User is not authorized to create tenant',
    EMAIL_REQUIRED: 'Email is required',
    USER_ALREADY_VERIFIED: 'User is already verified',
    TOKEN_REQUIRED: 'Token is required',
    INVALID_EXPIRED_TOKEN: 'Invalid or expired token',
    TOKEN_EXPIRED: 'Token has expired',
    USER_ALREADY_EXISTS: 'User already exists try logging in',
    INVALID_EXPIRED_REFRESH_TOKEN: 'Invalid or expired refresh token',
    REFRESH_TOKEN_NOT_FOUND: 'Refresh token not found',
    USER_NOT_AUTHENTICATED: 'User not authenticated',
    USER_EMAIL_NOT_VERIFIED: 'User email is not verified',
    INVALID_CREDENTIALS: 'Invalid credentials',
    TENANT_NOT_FOUND: 'Tenant not found',
    TENANT_NAME_TAKEN: 'Tenant name already taken',
    FAILED_TO_UPDATE_TENANT: 'Failed to update tenant',
    FAILED_TO_CREATE_TENANT: 'Failed to create tenant',
    USER_ALREADY_HAS_TENANT: 'User already has a tenant',
    INTERNAL_SERVER_ERROR: 'Internal server error',
    FAILED_TO_CREATE_USER: 'Failed to create user',
    FAILED_TO_UPDATE_USER: 'Failed to update user',
    USER_IS_BLOCKED: 'User is blocked',
    USER_IS_DELETED: 'User is deleted',
    UNIQUE_CONSTRAINT_VIOLATION: 'Unique constraint violation',
    SUBSCRIPTION_NOT_FOUND: 'Subscription not found',
    ONLY_IMAGE_FILES_ALLOWED: 'Only image files are allowed!',
    FILE_IS_REQUIRED: 'File is required',
    MACHINE_NOT_FOUND: 'Machine not found',
    MACHINE_NAME_TAKEN: 'Machine name already exists, try another one',
    FAILED_TO_CREATE_MACHINE: 'Failed to create machine',
    FAILED_TO_UPDATE_MACHINE: 'Failed to update machine',
    MACHINE_ALREADY_DELETED: 'Machine is already deleted',
    FIXTURE_NOT_FOUND: 'Fixture not found',
    FIXTURE_NAME_TAKEN: 'Fixture name already exists, try another one',
    FAILED_TO_CREATE_FIXTURE: 'Failed to create fixture',
    FAILED_TO_UPDATE_FIXTURE: 'Failed to update fixture',
    FIXTURE_ALREADY_DELETED: 'Fixture is already deleted',
    SUBSCRIPTION_EXPIRED:
      'Subscription has expired. Please upgrade to continue.',
    SUBSCRIPTION_RESTRICTED: 'Subscription is restricted. Access denied.',
    NO_SUBSCRIPTION_FOUND: 'No active subscription found for this tenant',
    TENANT_ID_MISSING: 'Tenant identification missing',
    FAILED_TO_CHECK_TENANT: 'Failed to check tenant',
    TENANT_IS_BLOCKED: 'Tenant is blocked',
  },
  VALIDATION: {
    EMAIL_INVALID: 'Please provide a valid email address',
    PASSWORD_MIN_LENGTH_8: 'Password must be at least 8 characters long',
    PASSWORD_MIN_LENGTH_6: 'Password must be at least 6 characters long',
    PASSWORD_MAX_LENGTH_12: 'Password must be at most 12 characters long',
    NAME_MIN_LENGTH_3: 'Name must be at least 3 characters long',
    NAME_MIN_LENGTH_2: 'Name must be at least 2 characters long',
    ROLE_INVALID: 'Invalid role',
  },
  SUCCESS: {
    USER_REGISTERED: 'User registered successfully',
    USER_CREATED: 'user sucessfully created this is from ApiResponse',
    USER_LOGGED_IN: 'user sucessfully logged in',
    USER_PROFILE: 'user profile',
    USER_UPDATED: 'user updated successfully',
    TOKEN_REFRESHED: 'token refreshed successfully',
    PASSWORD_RESET_LINK_SENT: 'Password reset link sent successfully',
    PASSWORD_RESET: 'Password reset successfully',
    EMAIL_VERIFIED: 'Email successfully verified',
    VERIFICATION_EMAIL_SENT: 'Verification email sent successfully',
    USER_LOGGED_OUT: 'user successfully logged out',
    TENANT_FETCHED: 'Tenant fetched successfully',
    TENANT_CREATED: 'Tenant created successfully',
    TENANT_UPDATED: 'Tenant updated successfully',
    ALL_TENANTS_FETCHED: 'All tenants fetched successfully',
    ALL_USERS_FETCHED: 'All users fetched successfully',
    TENANT_NAME_UPDATED: 'Tenant name updated successfully',
    SUBSCRIPTION_CREATED: 'Subscription created successfully',
    SUBSCRIPTION_FETCHED: 'Subscription fetched successfully',
    SUBSCRIPTION_UPDATED: 'Subscription updated successfully',
    PROFILE_IMAGE_UPLOADED: 'Profile image uploaded successfully',
    MACHINE_CREATED: 'Machine created successfully',
    MACHINE_UPDATED: 'Machine updated successfully',
    MACHINES_FETCHED: 'Machines fetched successfully',
    MACHINE_BLOCK_TOGGLED: 'Machine block status updated',
    MACHINE_DELETED: 'Machine deleted successfully',
    FIXTURE_CREATED: 'Fixture created successfully',
    FIXTURE_UPDATED: 'Fixture updated successfully',
    FIXTURES_FETCHED: 'Fixtures fetched successfully',
    FIXTURE_BLOCK_TOGGLED: 'Fixture block status updated',
    FIXTURE_DELETED: 'Fixture deleted successfully',
    USER_DELETED: 'User deleted successfully',
  },
};
