export enum RepositoryModelNames {
  USER = 'user',
  PLAN = 'plan',
  TENANT = 'tenant',
  FIXTURE = 'fixture',
  MACHINE = 'machine',
  PAYMENT = 'payment',
  SUBSCRIPTION = 'subscription',
  RAW_MATERIAL = 'rawMaterial',
  JOB = 'job',
  PART = 'part',
  LOOKUP = 'lookup',
  SHIFT_TEMPLATE = 'shiftTemplate',
  SHIFT_TEMPLATE_JOB = 'shiftTemplateJob',
  SHIFT_JOB = 'shiftJob',
  PRODUCTION_SHIFT = 'productionShift',
  NC_PROGRAM = 'ncProgram',
  PROGRAM_VERSION = 'programVersion',
}
